apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kkp26bc42-python 
  janus-idp.io/tekton: kkp26bc42-python
  backstage.io/kubernetes-id: kkp26bc42-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kkp26bc42-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  